### ISSUE TITLE
Guidance on package citations

### ISSUE THREAD

**Issue by sckott** [ropensci/dev_guide#115] opened 2019-01-16 17:09 UTC
see https://github.com/ropensci/software-review/issues/266#issuecomment-454489115 for a  discussion on this from one of our submissions

Should we suggest any best practice for package citations? If so, what?

**Comment by maelle** [comment] 2019-01-16 17:11
Maybe we can ask the community via the forum?

**Comment by sckott** [comment] 2019-01-16 17:36
sounds good

**Comment by sckott** [comment] 2019-01-16 18:06
https://discuss.ropensci.org/t/should-the-ropensci-dev-guide-include-package-citation-best-practices/1551

**Comment by maelle** [comment] 2019-04-30 09:29
@sckott @noamross (and others if you want to chime in!) any thoughts on https://discuss.ropensci.org/t/should-the-ropensci-dev-guide-include-package-citation-best-practices/1551/6?u=maelle? Thanks.

**Comment by sckott** [comment] 2019-05-02 15:19
yes, i think so

**Comment by maelle** [comment] 2019-05-14 07:09
@cboettig do you know of good CITATION files that I could use as examples to implement Noam's guidance (cf https://discuss.ropensci.org/t/should-the-ropensci-dev-guide-include-package-citation-best-practices/1551/4)?

**Comment by maelle** [comment] 2019-06-10 14:04
:wave: @cboettig, any tip? :smile_cat:

**Comment by maelle** [comment] 2019-06-19 15:12
Postponing this until we get/make an up-to-date Zenodo R client.

**Comment by stefaniebutland** [comment] 2020-05-29 19:52
Comments from working on Community Contributing Guide

Guidance on package citations is important to have! Having a section in the dev guide will allow me to link to it from contrib guide where I tell ppl the value of citing packages and resources. Could be done as for pkg maintenance chapter: publish a blog post, get feedback, add chapter. 

Notes from a convo with Karthik:
- Create a chapter in dev guide on how to make your software more citable. People might use our stuff without us knowing (e.g. discover and use via CRAN) so instruct them on how to get their stuff cited.
- Use citation file; don’t just rely on citation function to auto generate citation from DESCRIPTION file
- Archive in zenodo and add DOI
- If they write JOSS or other publication where they describe the software, then replace citation file with that citation
- Direct potential readers to the preferred citation in the README by adding boilerplate text “here’s how to cite my pkg”

from Ben Marwick on [Twitter](https://twitter.com/benmarwick/status/1261726909148233728):
> I've had success getting citations of my #rstats software by making it very clear to users that it is expected, & making it very easy for them to do it. For example, make the citation the 1st thing people see on your README & in the vignette, like this

**Comment by maelle** [comment] 2020-06-22 12:57
https://twitter.com/benmarwick/status/1261726909148233728

**Comment by maelle** [comment] 2020-06-22 12:58
from the user perspective https://github.com/Pakillo/grateful & https://github.com/dirkschumacher/thankr (not for the guide, for a blog post footnote/aside)

**Comment by maelle** [comment] 2020-06-22 13:01
https://twitter.com/pjs_228/status/1204838341461585921 & tidyverse JOSS paper & JOSS+rOpenSci (still for the post)

**Comment by maelle** [comment] 2020-06-22 13:01
the tweet that made so many people angry https://twitter.com/georgemsavva/status/1197122359515373574

**Comment by maelle** [comment] 2020-06-22 13:02
https://neuropsychology.github.io/psycho.R//2018/08/31/cite_packages.html

**Comment by maelle** [comment] 2020-06-22 14:07
`usethis::use_citation()` for when one wants to add something specific as a citation.

**Comment by maelle** [comment] 2020-06-22 14:19
https://discuss.ropensci.org/t/should-the-ropensci-dev-guide-include-package-citation-best-practices/1551/15 a Zenodo activation R function would add that base URL to the file (or to the clipboard)

**Comment by stefaniebutland** [comment] 2020-10-21 17:27
new preprint 
Katz DS, Chue Hong NP, Clark T et al. The importance of software citation [version 1; peer review: awaiting peer review]. F1000Research 2020, 9:1257 (https://doi.org/10.12688/f1000research.26932.1)

**Comment by Bisaloo** [comment] 2020-10-23 10:38
A related question: should original articles of the implemented method be included in the `CITATION` file? ([example](https://github.com/Bisaloo/asymptor/blob/main/inst/CITATION))

Or it is sufficient to say "Please also cite the original articles", without adding the full reference?

I believe both the original article and the package should always be cited but I'm having a hard time to figure out what is the job of the package developer vs the user to make sure this is the case.

**Comment by sckott** [comment] 2020-10-26 15:40
@Bisaloo  What do you mean by "original article of the implemented method" - that is the paper describing the R package?

**Comment by Bisaloo** [comment] 2020-10-26 15:52
No, I mean the paper describing the maths behind it, which can be written by different people than the package developer(s).

When the package focuses on a specific method, presented in a single paper, I feel kind of bad as a package developer if users use my package and do not credit the people that laid out the mathematical foundation behind the package.

I don't have the same issue when the package collates methods from multiple sources.

It might just be me being too cautious for no reason though :man_shrugging: .

**Comment by sckott** [comment] 2020-10-26 15:53
I've not thought deeply about this, maybe @cboettig can jump in here?

**Comment by maelle** [comment] 2020-11-05 08:37
@Bisaloo could you also post this question on the forum?

I can see your point. I am also wondering what happens if the CITATION file contains
* A "legit" looking citation to the mathematical paper
* The citation to the package
Does the user feel they can pick one? So you probably need some sort of sentence to clarify things?

Do you have an example of a CITATION file where you list the methodological paper?

**Comment by Bisaloo** [comment] 2020-11-05 08:56
@maelle, I'd be super grateful if you can copy/paste this question to the forum :pray:. I lost my password and it looks like my email provider is blocking the recovery email (I had a chat about this with Stefanie Butland but we didn't find a solution).

- Example of a CITATION file linking to the papers presenting the method:

https://github.com/Bisaloo/asymptor/blob/main/inst/CITATION

- Example of a CITATION file for a data package linking to the paper providing the data:

https://github.com/Bisaloo/contactdata/blob/main/inst/CITATION

**Comment by maelle** [comment] 2020-11-30 13:21
@Bisaloo if you end up posting on the forum, would you mind copy-pasting the link here?

**Comment by maelle** [comment] 2021-01-12 15:04
@Bisaloo following up on this, did you get help anywhere?

**Comment by maelle** [comment] 2021-01-12 15:41
I wonder if there have been surveys of scientists asking them why they (don't) cite packages/software in general. Most probably there have been such surveys. :thinking:

**Comment by stefaniebutland** [comment] 2021-01-12 17:00
I think Dan Katz is active in this area. He might know https://twitter.com/danielskatz

**Comment by maelle** [comment] 2021-01-14 12:45
https://twitter.com/FaustoBustos/status/1197124137078136832

**Comment by maelle** [comment] 2021-01-14 12:46
I also wonder what proportion of journals have a limit on number of citations :thinking:

**Comment by maelle** [comment] 2021-01-14 13:03
In papers, citing packages doesn't make the research reproducible. (writing this as a comment as often in the threads "reproducibility" is given as an argument for citing packages)

**Comment by maelle** [comment] 2021-01-14 13:21
not something we'd recommend but interesting https://twitter.com/d_olivaw/status/1261439521134182406

**Comment by maelle** [comment] 2021-01-14 13:24
"just a tool for accessing data" https://twitter.com/sk_emptyset/status/1261729463613693952

**Comment by maelle** [comment] 2021-01-14 13:40
I wonder if I can find the % of packages with a CITATION file, using pkgsearch.

**Comment by maelle** [comment] 2021-01-14 13:42
https://github.com/search?q=user%3Acran+path%3A%2Finst%2F+filename%3ACITATION&type=Code&ref=advsearch&l=&l=

**Comment by maelle** [comment] 2021-01-14 14:04
JSS citations https://github.com/search?q=JSS+user%3Acran+path%3A%2Finst%2F+filename%3ACITATION&type=Code
JOSS citations https://github.com/search?q=JOSS+user%3Acran+path%3A%2Finst%2F+filename%3ACITATION&type=Code

**Comment by maelle** [comment] 2021-01-14 14:50
from the contributing guide https://twitter.com/LeafyEricScott/status/1273605411577442304

**Comment by maelle** [comment] 2021-01-14 14:52
https://contributing.ropensci.org/resources.html#packages and https://contributing.ropensci.org/resources.html#devguide

**Comment by maelle** [comment] 2021-01-14 14:57
https://f1000research.com/articles/9-1257

**Comment by maelle** [comment] 2021-01-14 15:08
https://arxiv.org/abs/1911.00295

**Comment by maelle** [comment] 2021-01-14 15:16
re-mention aut vs ctb

**Comment by Bisaloo** [comment] 2021-01-16 10:45
> @Bisaloo if you end up posting on the forum, would you mind copy-pasting the link here?

https://discuss.ropensci.org/t/citation-of-original-article-when-implementing-specific-method/2312

**Comment by maelle** [comment] 2021-01-16 12:09
tech note draft https://github.com/ropensci/roweb3/pull/116

**Comment by maelle** [comment] 2021-03-23 12:25
Tech note https://ropensci.org/blog/2021/02/16/package-citation/

**Comment by maelle** [comment] 2021-04-02 09:21
fixed in dev

**Closed by maelle** 2021-04-02 09:21 UTC
Labels: content :page_with_curl:
